apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # Base64 encoded MongoDB connection string
  # You should use proper secret management in production
  MONGO_URI: bW9uZ29kYitzcnY6Ly8yMjUyMTQzMDpLa201MllBVlhQNllwdEZAY2hhdGFwcC5vNXo3bC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Y2hhdGFwcA==