apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
spec:
  template:
    spec:
      containers:
        - name: redis-tools
          image: redis:6.2-alpine
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"
          command:
            - sh
            - -c
            - |
              # Cài bind-tools
              apk add --no-cache bind-tools

              # Đợi Redis pods sẵn sàng
              echo "Waiting for Redis pods to be ready..."
              sleep 0

              # Debug DNS
              echo "=== Debug DNS ==="
              cat /etc/resolv.conf
              echo "=== Testing DNS resolution ==="
              nslookup redis-cluster-headless.default.svc.cluster.local

              # Lấy IP của các Redis pods từ service headless
              echo "Getting Redis pod IPs..."
              nodes=""
              ips=$(nslookup redis-cluster-headless.default.svc.cluster.local | grep Address | grep -v "10.96.0.10" | awk '{print $2}')

              for ip in $ips; do
                echo "Found Redis node at $ip"
                nodes="$nodes $ip:6379"
              done

              if [ -z "$nodes" ]; then
                echo "No Redis nodes found. Exiting..."
                exit 1
              fi

              echo "Creating cluster with nodes: $nodes"
              redis-cli --cluster create $nodes --cluster-replicas 1 --cluster-yes

              # Giữ container không exit ngay
              sleep infinity
      restartPolicy: OnFailure
