apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  selector:
    matchLabels:
      app: chat-app
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: chat-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "5000"
            - name: REDIS_HOST_1
              value: "redis-cluster-0.redis-cluster-headless"
            - name: REDIS_PORT_1
              value: "6379"
            - name: REDIS_HOST_2
              value: "redis-cluster-1.redis-cluster-headless"
            - name: REDIS_PORT_2
              value: "6379"
            - name: REDIS_HOST_3
              value: "redis-cluster-2.redis-cluster-headless"
            - name: REDIS_PORT_3
              value: "6379"
            - name: REDIS_HOST_4
              value: "redis-cluster-3.redis-cluster-headless"
            - name: REDIS_PORT_4
              value: "6379"
            - name: REDIS_HOST_5
              value: "redis-cluster-4.redis-cluster-headless"
            - name: REDIS_PORT_5
              value: "6379"
            - name: REDIS_HOST_6
              value: "redis-cluster-5.redis-cluster-headless"
            - name: REDIS_PORT_6
              value: "6379"
            - name: MONGO_URI
              value: "mongodb+srv://22521430:Kkm52YAVXP6YptF@chatapp.o5z7l.mongodb.net/?retryWrites=true&w=majority&appName=chatapp"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  selector:
    app: chat-app
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
